apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue
    app.kubernetes.io/part-of: ecommerce
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
        app.kubernetes.io/part-of: ecommerce
    spec:
      containers:
      - image: ecommerce-catalogue:0.0.1-SNAPSHOT
        name: catalogue
        env:
          - name: server.port
            value: "8080"
          - name: management.server.port
            value: "8081"
          - name: spring.profiles.active
            value: admin
          - name: logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter
            value: DEBUG
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: catalogue
